/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/drm_fabric.yaml */
/* YNL-GEN uapi header */
/* To regenerate run: tools/net/ynl/ynl-regen.sh */

#ifndef _UAPI_LINUX_DRM_FABRIC_H
#define _UAPI_LINUX_DRM_FABRIC_H

#define DRM_FABRIC_FAMILY_NAME		"drm-fabric"
#define DRM_FABRIC_FAMILY_VERSION	1

/*
 * Fabric interconnect technology. New types are added with the provider that
 * first reports them. Zero is not a valid type.
 */
enum drm_fabric_type {
	DRM_FABRIC_TYPE_SYNTHETIC = 1,
};

/*
 * Operational (link) state of a port, as observed by the driver.
 */
enum drm_fabric_port_state {
	DRM_FABRIC_PORT_STATE_UNKNOWN,
	DRM_FABRIC_PORT_STATE_INACTIVE,
	DRM_FABRIC_PORT_STATE_ACTIVE,
	DRM_FABRIC_PORT_STATE_DEGRADED,
};

/*
 * Kind of device directly adjacent at a port's far end.
 */
enum drm_fabric_peer_type {
	DRM_FABRIC_PEER_TYPE_ACCEL = 1,
	DRM_FABRIC_PEER_TYPE_SWITCH,
};

enum drm_fabric_a {
	DRM_FABRIC_A_FABRIC = 1,
	DRM_FABRIC_A_ENDPOINT,
	DRM_FABRIC_A_PORT,
	DRM_FABRIC_A_PORT_STATS,
	DRM_FABRIC_A_FABRIC_ID,
	DRM_FABRIC_A_ENDPOINT_ID,
	DRM_FABRIC_A_PORT_INDEX,
	DRM_FABRIC_A_DEV_NAME,
	DRM_FABRIC_A_BUS_NAME,
	DRM_FABRIC_A_PEER,
	DRM_FABRIC_A_TOPOLOGY_GENERATION,

	__DRM_FABRIC_A_MAX,
	DRM_FABRIC_A_MAX = (__DRM_FABRIC_A_MAX - 1)
};

enum drm_fabric_a_fabric_attrs {
	DRM_FABRIC_A_FABRIC_ATTRS_PAD = 1,
	DRM_FABRIC_A_FABRIC_ATTRS_FABRIC_ID,
	DRM_FABRIC_A_FABRIC_ATTRS_TYPE,
	DRM_FABRIC_A_FABRIC_ATTRS_NAME,
	DRM_FABRIC_A_FABRIC_ATTRS_INSTANCE_ID,

	__DRM_FABRIC_A_FABRIC_ATTRS_MAX,
	DRM_FABRIC_A_FABRIC_ATTRS_MAX = (__DRM_FABRIC_A_FABRIC_ATTRS_MAX - 1)
};

enum drm_fabric_a_endpoint_attrs {
	DRM_FABRIC_A_ENDPOINT_ATTRS_PAD = 1,
	DRM_FABRIC_A_ENDPOINT_ATTRS_ENDPOINT_ID,
	DRM_FABRIC_A_ENDPOINT_ATTRS_FABRIC_ID,
	DRM_FABRIC_A_ENDPOINT_ATTRS_FABRIC_EP_ID,
	DRM_FABRIC_A_ENDPOINT_ATTRS_NAME,
	DRM_FABRIC_A_ENDPOINT_ATTRS_DEV_NAME,
	DRM_FABRIC_A_ENDPOINT_ATTRS_BUS_NAME,

	__DRM_FABRIC_A_ENDPOINT_ATTRS_MAX,
	DRM_FABRIC_A_ENDPOINT_ATTRS_MAX = (__DRM_FABRIC_A_ENDPOINT_ATTRS_MAX - 1)
};

enum drm_fabric_a_port_attrs {
	DRM_FABRIC_A_PORT_ATTRS_PORT_INDEX = 1,
	DRM_FABRIC_A_PORT_ATTRS_ENDPOINT_ID,
	DRM_FABRIC_A_PORT_ATTRS_OPER_STATE,
	DRM_FABRIC_A_PORT_ATTRS_MAX_LANE_COUNT,
	DRM_FABRIC_A_PORT_ATTRS_MAX_LANE_SIGNALING_RATE_MBPS,
	DRM_FABRIC_A_PORT_ATTRS_PEER,

	__DRM_FABRIC_A_PORT_ATTRS_MAX,
	DRM_FABRIC_A_PORT_ATTRS_MAX = (__DRM_FABRIC_A_PORT_ATTRS_MAX - 1)
};

enum drm_fabric_a_peer_attrs {
	DRM_FABRIC_A_PEER_ATTRS_PAD = 1,
	DRM_FABRIC_A_PEER_ATTRS_PEER_ID,
	DRM_FABRIC_A_PEER_ATTRS_TYPE,
	DRM_FABRIC_A_PEER_ATTRS_PORT_INDEX,

	__DRM_FABRIC_A_PEER_ATTRS_MAX,
	DRM_FABRIC_A_PEER_ATTRS_MAX = (__DRM_FABRIC_A_PEER_ATTRS_MAX - 1)
};

enum drm_fabric_a_port_stats_attrs {
	DRM_FABRIC_A_PORT_STATS_ATTRS_PAD = 1,
	DRM_FABRIC_A_PORT_STATS_ATTRS_ENDPOINT_ID,
	DRM_FABRIC_A_PORT_STATS_ATTRS_PORT_INDEX,
	DRM_FABRIC_A_PORT_STATS_ATTRS_READ_BYTES,
	DRM_FABRIC_A_PORT_STATS_ATTRS_WRITE_BYTES,
	DRM_FABRIC_A_PORT_STATS_ATTRS_LINK_DOWN_COUNT,
	DRM_FABRIC_A_PORT_STATS_ATTRS_RETRAIN_COUNT,

	__DRM_FABRIC_A_PORT_STATS_ATTRS_MAX,
	DRM_FABRIC_A_PORT_STATS_ATTRS_MAX = (__DRM_FABRIC_A_PORT_STATS_ATTRS_MAX - 1)
};

enum drm_fabric_cmd {
	DRM_FABRIC_CMD_FABRIC_GET = 1,
	DRM_FABRIC_CMD_ENDPOINT_GET,
	DRM_FABRIC_CMD_PORT_GET,
	DRM_FABRIC_CMD_PORT_STATS_GET,
	DRM_FABRIC_CMD_PORT_CHANGE_NTF,
	DRM_FABRIC_CMD_PORT_PEER_CREATE_NTF,
	DRM_FABRIC_CMD_PORT_PEER_DELETE_NTF,
	DRM_FABRIC_CMD_ENDPOINT_CREATE_NTF,
	DRM_FABRIC_CMD_ENDPOINT_DELETE_NTF,
	DRM_FABRIC_CMD_FABRIC_CREATE_NTF,
	DRM_FABRIC_CMD_FABRIC_DELETE_NTF,

	__DRM_FABRIC_CMD_MAX,
	DRM_FABRIC_CMD_MAX = (__DRM_FABRIC_CMD_MAX - 1)
};

#define DRM_FABRIC_MCGRP_MONITOR	"monitor"

#endif /* _UAPI_LINUX_DRM_FABRIC_H */
